/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { Message } from './Message';
export type Choice = {
    /**
     * The index of the choice in the list of choices (always 0).
     */
    index: number;
    /**
     * A chat completion message generated by the model.
     */
    message: Message;
    /**
     * The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence, or `length` if the maximum number of tokens specified in the request was reached.
     */
    finish_reason?: ('stop' | 'length' | null);
};

