// @generated by protoc-gen-es v2.13.0 with parameter "target=ts"
// @generated from file exa/seat_management_pb/seat_management.proto (package exa.seat_management_pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Metadata, PlanInfo, UserStatus } from "../codeium_common_pb/codeium_common_pb";
import { file_exa_codeium_common_pb_codeium_common } from "../codeium_common_pb/codeium_common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file exa/seat_management_pb/seat_management.proto.
 */
export const file_exa_seat_management_pb_seat_management: GenFile = /*@__PURE__*/
  fileDesc("CixleGEvc2VhdF9tYW5hZ2VtZW50X3BiL3NlYXRfbWFuYWdlbWVudC5wcm90bxIWZXhhLnNlYXRfbWFuYWdlbWVudF9wYiJJChRHZXRVc2VyU3RhdHVzUmVxdWVzdBIxCghtZXRhZGF0YRgBIAEoCzIfLmV4YS5jb2RlaXVtX2NvbW1vbl9wYi5NZXRhZGF0YSKDAQoVR2V0VXNlclN0YXR1c1Jlc3BvbnNlEjYKC3VzZXJfc3RhdHVzGAEgASgLMiEuZXhhLmNvZGVpdW1fY29tbW9uX3BiLlVzZXJTdGF0dXMSMgoJcGxhbl9pbmZvGAIgASgLMh8uZXhhLmNvZGVpdW1fY29tbW9uX3BiLlBsYW5JbmZvYgZwcm90bzM", [file_exa_codeium_common_pb_codeium_common]);

/**
 * @generated from message exa.seat_management_pb.GetUserStatusRequest
 */
export type GetUserStatusRequest = Message<"exa.seat_management_pb.GetUserStatusRequest"> & {
  /**
   * @generated from field: exa.codeium_common_pb.Metadata metadata = 1;
   */
  metadata?: Metadata | undefined;
};

/**
 * Describes the message exa.seat_management_pb.GetUserStatusRequest.
 * Use `create(GetUserStatusRequestSchema)` to create a new message.
 */
export const GetUserStatusRequestSchema: GenMessage<GetUserStatusRequest> = /*@__PURE__*/
  messageDesc(file_exa_seat_management_pb_seat_management, 0);

/**
 * @generated from message exa.seat_management_pb.GetUserStatusResponse
 */
export type GetUserStatusResponse = Message<"exa.seat_management_pb.GetUserStatusResponse"> & {
  /**
   * @generated from field: exa.codeium_common_pb.UserStatus user_status = 1;
   */
  userStatus?: UserStatus | undefined;

  /**
   * @generated from field: exa.codeium_common_pb.PlanInfo plan_info = 2;
   */
  planInfo?: PlanInfo | undefined;
};

/**
 * Describes the message exa.seat_management_pb.GetUserStatusResponse.
 * Use `create(GetUserStatusResponseSchema)` to create a new message.
 */
export const GetUserStatusResponseSchema: GenMessage<GetUserStatusResponse> = /*@__PURE__*/
  messageDesc(file_exa_seat_management_pb_seat_management, 1);

