// AUTO-GENERATED by scripts/generate-legacy-pi-bundled-registry.ts.
// Do not edit by hand — run `bun scripts/generate-legacy-pi-bundled-registry.ts --generate`.
/**
 * Static handles on every bundled `@oh-my-pi/pi-*` surface — package
 * roots plus every non-wildcard subpath export declared in each package's
 * `exports` field. Loaded lazily by `legacy-pi-compat.ts` in compiled-binary
 * mode (issue #3423) and re-exported through the `omp-legacy-pi-bundled:`
 * virtual namespace — bunfs paths cannot be resolved at runtime on Bun
 * 1.3.14+, so the only way to re-route extension imports onto the host's
 * in-process copy is via live module references captured at compile time.
 *
 * This module is split out from `legacy-pi-compat.ts` so dev/test runs that
 * touch the compat layer never trigger the cascade through
 * `legacy-pi-coding-agent-shim.ts → ../index → export/html/...` (which
 * requires generated artifacts that only exist after a `bun run build`).
 *
 * The bundler reaches every entry below via standard static-import analysis,
 * so no `--compile` extras are required in `scripts/build-binary.ts`.
 */
import * as bundledPiAgentCore from "@oh-my-pi/pi-agent-core";
import * as bundledPiAgentCoreCompaction from "@oh-my-pi/pi-agent-core/compaction";
import * as bundledPiAiAuthBroker from "@oh-my-pi/pi-ai/auth-broker";
import * as bundledPiAiAuthGateway from "@oh-my-pi/pi-ai/auth-gateway";
import * as bundledPiAiDialect from "@oh-my-pi/pi-ai/dialect";
import * as bundledPiAiOauth from "@oh-my-pi/pi-ai/oauth";
import * as bundledPiAiRegistry from "@oh-my-pi/pi-ai/registry";
import * as bundledPiAiRegistryOauth from "@oh-my-pi/pi-ai/registry/oauth";
import * as bundledPiAiUtilsHarmonyLeak from "@oh-my-pi/pi-ai/utils/harmony-leak";
import * as bundledPiAiUtilsSchema from "@oh-my-pi/pi-ai/utils/schema";
import * as bundledPiCodingAgentAsync from "@oh-my-pi/pi-coding-agent/async";
import * as bundledPiCodingAgentAutoresearch from "@oh-my-pi/pi-coding-agent/autoresearch";
import * as bundledPiCodingAgentCapability from "@oh-my-pi/pi-coding-agent/capability";
import * as bundledPiCodingAgentCliGalleryFixtures from "@oh-my-pi/pi-coding-agent/cli/gallery-fixtures";
import * as bundledPiCodingAgentCommit from "@oh-my-pi/pi-coding-agent/commit";
import * as bundledPiCodingAgentCommitAgentic from "@oh-my-pi/pi-coding-agent/commit/agentic";
import * as bundledPiCodingAgentCommitAgenticTools from "@oh-my-pi/pi-coding-agent/commit/agentic/tools";
import * as bundledPiCodingAgentCommitAnalysis from "@oh-my-pi/pi-coding-agent/commit/analysis";
import * as bundledPiCodingAgentCommitChangelog from "@oh-my-pi/pi-coding-agent/commit/changelog";
import * as bundledPiCodingAgentCommitMapReduce from "@oh-my-pi/pi-coding-agent/commit/map-reduce";
import * as bundledPiCodingAgentDap from "@oh-my-pi/pi-coding-agent/dap";
import * as bundledPiCodingAgentDebug from "@oh-my-pi/pi-coding-agent/debug";
import * as bundledPiCodingAgentDiscovery from "@oh-my-pi/pi-coding-agent/discovery";
import * as bundledPiCodingAgentEdit from "@oh-my-pi/pi-coding-agent/edit";
import * as bundledPiCodingAgentEval from "@oh-my-pi/pi-coding-agent/eval";
import * as bundledPiCodingAgentExa from "@oh-my-pi/pi-coding-agent/exa";
import * as bundledPiCodingAgentExportHtml from "@oh-my-pi/pi-coding-agent/export/html";
import * as bundledPiCodingAgentExtensibilityCustomCommands from "@oh-my-pi/pi-coding-agent/extensibility/custom-commands";
import * as bundledPiCodingAgentExtensibilityCustomCommandsBundledCiGreen from "@oh-my-pi/pi-coding-agent/extensibility/custom-commands/bundled/ci-green";
import * as bundledPiCodingAgentExtensibilityCustomCommandsBundledReview from "@oh-my-pi/pi-coding-agent/extensibility/custom-commands/bundled/review";
import * as bundledPiCodingAgentExtensibilityCustomTools from "@oh-my-pi/pi-coding-agent/extensibility/custom-tools";
import * as bundledPiCodingAgentExtensibilityExtensions from "@oh-my-pi/pi-coding-agent/extensibility/extensions";
import * as bundledPiCodingAgentExtensibilityHooks from "@oh-my-pi/pi-coding-agent/extensibility/hooks";
import * as bundledPiCodingAgentExtensibilityPlugins from "@oh-my-pi/pi-coding-agent/extensibility/plugins";
import * as bundledPiCodingAgentExtensibilityPluginsMarketplace from "@oh-my-pi/pi-coding-agent/extensibility/plugins/marketplace";
import * as bundledPiCodingAgentHindsight from "@oh-my-pi/pi-coding-agent/hindsight";
import * as bundledPiCodingAgentInternalUrls from "@oh-my-pi/pi-coding-agent/internal-urls";
import * as bundledPiCodingAgentLsp from "@oh-my-pi/pi-coding-agent/lsp";
import * as bundledPiCodingAgentLspClients from "@oh-my-pi/pi-coding-agent/lsp/clients";
import * as bundledPiCodingAgentMcp from "@oh-my-pi/pi-coding-agent/mcp";
import * as bundledPiCodingAgentMcpTransports from "@oh-my-pi/pi-coding-agent/mcp/transports";
import * as bundledPiCodingAgentMemories from "@oh-my-pi/pi-coding-agent/memories";
import * as bundledPiCodingAgentMemoryBackend from "@oh-my-pi/pi-coding-agent/memory-backend";
import * as bundledPiCodingAgentModes from "@oh-my-pi/pi-coding-agent/modes";
import * as bundledPiCodingAgentModesAcp from "@oh-my-pi/pi-coding-agent/modes/acp";
import * as bundledPiCodingAgentModesComponents from "@oh-my-pi/pi-coding-agent/modes/components";
import * as bundledPiCodingAgentModesComponentsExtensions from "@oh-my-pi/pi-coding-agent/modes/components/extensions";
import * as bundledPiCodingAgentModesComponentsStatusLine from "@oh-my-pi/pi-coding-agent/modes/components/status-line";
import * as bundledPiCodingAgentModesSetupWizard from "@oh-my-pi/pi-coding-agent/modes/setup-wizard";
import * as bundledPiCodingAgentModesThemeDefaults from "@oh-my-pi/pi-coding-agent/modes/theme/defaults";
import * as bundledPiCodingAgentSecrets from "@oh-my-pi/pi-coding-agent/secrets";
import * as bundledPiCodingAgentStt from "@oh-my-pi/pi-coding-agent/stt";
import * as bundledPiCodingAgentTask from "@oh-my-pi/pi-coding-agent/task";
import * as bundledPiCodingAgentTools from "@oh-my-pi/pi-coding-agent/tools";
import * as bundledPiCodingAgentTui from "@oh-my-pi/pi-coding-agent/tui";
import * as bundledPiCodingAgentWebScrapers from "@oh-my-pi/pi-coding-agent/web/scrapers";
import * as bundledPiCodingAgentWebSearch from "@oh-my-pi/pi-coding-agent/web/search";
import * as bundledPiNatives from "@oh-my-pi/pi-natives";
import * as bundledPiTui from "@oh-my-pi/pi-tui";
import * as bundledPiUtils from "@oh-my-pi/pi-utils";
import * as bundledPiAi from "../legacy-pi-ai-shim";
import * as bundledPiCodingAgent from "../legacy-pi-coding-agent-shim";
import * as bundledTypeBoxShim from "../typebox";

/**
 * Canonical specifier → live module namespace. Keys MUST match the right-hand
 * side of `bundledRegistryVirtualSpecifier(...)` calls in
 * `legacy-pi-compat.ts`; the synthesizer enumerates each namespace's own
 * enumerable exports at extension load time. The companion
 * `legacy-pi-bundled-keys.ts` mirrors `Object.keys(BUNDLED_PI_REGISTRY)` and
 * is statically imported by `legacy-pi-compat.ts` to seed the override map
 * without paying the cascade above.
 */
export const BUNDLED_PI_REGISTRY: Readonly<Record<string, Readonly<Record<string, unknown>>>> = {
	"@oh-my-pi/pi-agent-core": bundledPiAgentCore as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-agent-core/compaction": bundledPiAgentCoreCompaction as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-ai": bundledPiAi as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-ai/auth-broker": bundledPiAiAuthBroker as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-ai/auth-gateway": bundledPiAiAuthGateway as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-ai/utils/harmony-leak": bundledPiAiUtilsHarmonyLeak as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-ai/dialect": bundledPiAiDialect as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-ai/oauth": bundledPiAiOauth as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-ai/registry": bundledPiAiRegistry as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-ai/registry/oauth": bundledPiAiRegistryOauth as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-ai/utils/schema": bundledPiAiUtilsSchema as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent": bundledPiCodingAgent as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/async": bundledPiCodingAgentAsync as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/autoresearch": bundledPiCodingAgentAutoresearch as unknown as Readonly<
		Record<string, unknown>
	>,
	"@oh-my-pi/pi-coding-agent/capability": bundledPiCodingAgentCapability as unknown as Readonly<
		Record<string, unknown>
	>,
	"@oh-my-pi/pi-coding-agent/cli/gallery-fixtures": bundledPiCodingAgentCliGalleryFixtures as unknown as Readonly<
		Record<string, unknown>
	>,
	"@oh-my-pi/pi-coding-agent/commit": bundledPiCodingAgentCommit as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/commit/agentic": bundledPiCodingAgentCommitAgentic as unknown as Readonly<
		Record<string, unknown>
	>,
	"@oh-my-pi/pi-coding-agent/commit/agentic/tools": bundledPiCodingAgentCommitAgenticTools as unknown as Readonly<
		Record<string, unknown>
	>,
	"@oh-my-pi/pi-coding-agent/commit/analysis": bundledPiCodingAgentCommitAnalysis as unknown as Readonly<
		Record<string, unknown>
	>,
	"@oh-my-pi/pi-coding-agent/commit/changelog": bundledPiCodingAgentCommitChangelog as unknown as Readonly<
		Record<string, unknown>
	>,
	"@oh-my-pi/pi-coding-agent/commit/map-reduce": bundledPiCodingAgentCommitMapReduce as unknown as Readonly<
		Record<string, unknown>
	>,
	"@oh-my-pi/pi-coding-agent/dap": bundledPiCodingAgentDap as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/debug": bundledPiCodingAgentDebug as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/discovery": bundledPiCodingAgentDiscovery as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/edit": bundledPiCodingAgentEdit as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/exa": bundledPiCodingAgentExa as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/export/html": bundledPiCodingAgentExportHtml as unknown as Readonly<
		Record<string, unknown>
	>,
	"@oh-my-pi/pi-coding-agent/extensibility/custom-commands":
		bundledPiCodingAgentExtensibilityCustomCommands as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/extensibility/custom-commands/bundled/ci-green":
		bundledPiCodingAgentExtensibilityCustomCommandsBundledCiGreen as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/extensibility/custom-commands/bundled/review":
		bundledPiCodingAgentExtensibilityCustomCommandsBundledReview as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/extensibility/custom-tools":
		bundledPiCodingAgentExtensibilityCustomTools as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/extensibility/extensions":
		bundledPiCodingAgentExtensibilityExtensions as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/extensibility/hooks": bundledPiCodingAgentExtensibilityHooks as unknown as Readonly<
		Record<string, unknown>
	>,
	"@oh-my-pi/pi-coding-agent/extensibility/plugins": bundledPiCodingAgentExtensibilityPlugins as unknown as Readonly<
		Record<string, unknown>
	>,
	"@oh-my-pi/pi-coding-agent/extensibility/plugins/marketplace":
		bundledPiCodingAgentExtensibilityPluginsMarketplace as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/internal-urls": bundledPiCodingAgentInternalUrls as unknown as Readonly<
		Record<string, unknown>
	>,
	"@oh-my-pi/pi-coding-agent/eval": bundledPiCodingAgentEval as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/lsp": bundledPiCodingAgentLsp as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/lsp/clients": bundledPiCodingAgentLspClients as unknown as Readonly<
		Record<string, unknown>
	>,
	"@oh-my-pi/pi-coding-agent/mcp": bundledPiCodingAgentMcp as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/mcp/transports": bundledPiCodingAgentMcpTransports as unknown as Readonly<
		Record<string, unknown>
	>,
	"@oh-my-pi/pi-coding-agent/memories": bundledPiCodingAgentMemories as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/memory-backend": bundledPiCodingAgentMemoryBackend as unknown as Readonly<
		Record<string, unknown>
	>,
	"@oh-my-pi/pi-coding-agent/hindsight": bundledPiCodingAgentHindsight as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/modes": bundledPiCodingAgentModes as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/modes/acp": bundledPiCodingAgentModesAcp as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/modes/components": bundledPiCodingAgentModesComponents as unknown as Readonly<
		Record<string, unknown>
	>,
	"@oh-my-pi/pi-coding-agent/modes/components/extensions":
		bundledPiCodingAgentModesComponentsExtensions as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/modes/components/status-line":
		bundledPiCodingAgentModesComponentsStatusLine as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/modes/setup-wizard": bundledPiCodingAgentModesSetupWizard as unknown as Readonly<
		Record<string, unknown>
	>,
	"@oh-my-pi/pi-coding-agent/modes/theme/defaults": bundledPiCodingAgentModesThemeDefaults as unknown as Readonly<
		Record<string, unknown>
	>,
	"@oh-my-pi/pi-coding-agent/secrets": bundledPiCodingAgentSecrets as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/stt": bundledPiCodingAgentStt as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/task": bundledPiCodingAgentTask as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/tools": bundledPiCodingAgentTools as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/tui": bundledPiCodingAgentTui as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-coding-agent/web/scrapers": bundledPiCodingAgentWebScrapers as unknown as Readonly<
		Record<string, unknown>
	>,
	"@oh-my-pi/pi-coding-agent/web/search": bundledPiCodingAgentWebSearch as unknown as Readonly<
		Record<string, unknown>
	>,
	"@oh-my-pi/pi-natives": bundledPiNatives as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-tui": bundledPiTui as unknown as Readonly<Record<string, unknown>>,
	"@oh-my-pi/pi-utils": bundledPiUtils as unknown as Readonly<Record<string, unknown>>,
	typebox: bundledTypeBoxShim as unknown as Readonly<Record<string, unknown>>,
};
