//! Native utilities exported via N-API for the Oh My Pi toolchain.
//!
//! # Overview
//! High-performance primitives for clipboard access, grep, file discovery,
//! ANSI-aware text measurement, syntax highlighting, HTML-to-Markdown
//! conversion, and terminal SIXEL encoding.
//!
//! # Example
//! ```ignore
//! use pi_natives::text::visible_width;
//!
//! let width = visible_width("hello");
//! assert_eq!(width, 5);
//! ```
//!
//! # Architecture
//! ```text
//! JS (packages/natives) -> N-API -> Rust modules (clipboard/fd/glob/grep/html/highlight/sixel/text)
//! ```

#![allow(clippy::trailing_empty_array, reason = "generated by napi macro")]
#![allow(clippy::trivially_copy_pass_by_ref, reason = "napi env idiom")]
#![feature(alloc_error_hook)]

pub mod appearance;
pub mod ast;
pub mod block;
pub mod clipboard;
pub mod crash_handler;
pub mod fd;
pub mod fs_cache;
pub mod glob;
pub mod glob_util;
pub mod grep;
pub mod highlight;
pub mod html;
pub mod keys;
pub mod sixel;
pub mod snapcompact;
pub use pi_ast::language;

pub mod power;

pub mod iso;
pub mod prof;
pub mod ps;
pub mod pty;
pub mod shell;
pub mod summary;
pub mod task;
pub mod text;
pub mod tokens;
pub(crate) mod utils;
pub mod workspace;

use napi::bindgen_prelude::create_custom_tokio_runtime;
use napi_derive::{module_init, napi};
use tokio::runtime::{Builder, Runtime};

/// Version sentinel — exists solely so the JS loader can prove at load time
/// that the `.node` file on disk is from the same package release as the
/// `index.js` ESM wrapper invoking it.
///
/// The `js_name` is bumped by `scripts/release.ts` to match the new
/// `Cargo.toml` / `package.json` version on every release. The JS loader
/// computes the expected name from `package.json#version` and refuses to use
/// a `.node` that doesn't expose it, turning the silent
/// `<sym> is not a function` crash from a locked-file update (the canonical
/// Windows `bun install -g` failure mode) into a clear load-time error.
///
/// Bump policy: `__piNativesV{major}_{minor}_{patch}` — non-alphanumerics in
/// the version string are mapped to `_` to keep it a valid JS identifier.
/// MUST stay in sync with `VERSION_SENTINEL_EXPORT` in
/// `packages/natives/native/index.js` (which derives the name from
/// `package.json#version`).
#[napi(js_name = "__piNativesV15_12_5")]
pub const fn pi_natives_version_sentinel() {}

const NAPI_TOKIO_WORKER_THREADS: usize = 1;
const NAPI_TOKIO_MAX_BLOCKING_THREADS: usize = 4;
const NAPI_TOKIO_THREAD_STACK_SIZE: usize = 1024 * 1024;

fn build_napi_tokio_runtime() -> std::io::Result<Runtime> {
	Builder::new_multi_thread()
		.enable_all()
		.worker_threads(NAPI_TOKIO_WORKER_THREADS)
		.max_blocking_threads(NAPI_TOKIO_MAX_BLOCKING_THREADS)
		.thread_stack_size(NAPI_TOKIO_THREAD_STACK_SIZE)
		.thread_name("pi-natives-tokio")
		.build()
}

/// Native module entry point: install crash diagnostics and replace napi-rs's
/// default Tokio runtime before any async export can initialize it.
#[module_init]
fn initialize_native_module() {
	crash_handler::install();
	create_custom_tokio_runtime(
		build_napi_tokio_runtime().expect("create pi-natives napi Tokio runtime"),
	);
}

#[cfg(test)]
mod tests {
	use super::build_napi_tokio_runtime;

	#[test]
	fn napi_tokio_runtime_drives_async_and_blocking_tasks() {
		let runtime = build_napi_tokio_runtime().expect("runtime builds");
		let thread_name = runtime.block_on(async {
			tokio::task::spawn_blocking(|| std::thread::current().name().map(str::to_owned))
				.await
				.expect("blocking task joins")
		});

		assert_eq!(thread_name.as_deref(), Some("pi-natives-tokio"));
	}
}
