// Regenerate ranch/range/ui/src/lib/ports.ts from config/ports.env.
//
// The master UI is a vite app, so it cannot read a file at runtime; the values
// have to be in the bundle. They used to be hand-typed into surfaces.ts, 49
// literals that could drift from the SSOT silently. This makes the drift
// impossible: the file is generated, and the numbers come from the one source.
//
// Run:  bun run scripts/sync-ui-ports.ts
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = "/home/toxic/estate";
const SRC = join(ROOT, "config/ports.env");
const OUT = join(ROOT, "ranch/range/ui/src/lib/ports.ts");

const ports: Record<string, number> = {};
for (const line of readFileSync(SRC, "utf8").split("\n")) {
  if (!line || line.trimStart().startsWith("#")) continue;
  const eq = line.indexOf("=");
  if (eq < 0) continue;
  const key = line.slice(0, eq).trim();
  const value = Number.parseInt(line.slice(eq + 1).trim(), 10);
  if (!/^[A-Z0-9_]+$/.test(key) || !Number.isFinite(value)) continue;
  ports[key] = value;
}

const keys = Object.keys(ports).sort();
const width = Math.max(...keys.map((k) => k.length));
const rows = keys.map((k) => `\t${k}: ${ports[k]},`).join("\n");

const file = `// Ports come from config/ports.env and nowhere else (CONVENTIONS.md Rule 5.1).
//
// surfaces.ts used to carry 49 \`loopback(25100)\`-style literals. That is the same
// duplication that let .env and config/tau/.env contradict the SSOT: a port gets
// moved and the dashboard silently frames a dead address.
//
// GENERATED by scripts/sync-ui-ports.ts — do not hand-edit. A key that is not in
// the SSOT throws at module load, so a typo is a build failure rather than a
// frame pointed at nothing.

/** key -> port, verbatim from config/ports.env. */
export const PORTS = {
${rows}
} as const;

export type PortKey = keyof typeof PORTS;

/** Loopback origin for a port key. */
export function loopback(key: PortKey): string {
	const port = PORTS[key];
	if (port === undefined) {
		throw new Error(
			\`\${key} is not in config/ports.env. Add it there and re-run sync-ui-ports.ts.\`,
		);
	}
	return \`http://127.0.0.1:\${port}\`;
}
`;

writeFileSync(OUT, file);
console.log(`wrote ${keys.length} ports to ${OUT}`);